// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace Automaton_3000ML.Model
{
    public class ModelInput
    {
        [ColumnName("Label"), LoadColumn(0)]
        public float Label { get; set; }


        [ColumnName("SkillsCount"), LoadColumn(1)]
        public float SkillsCount { get; set; }


        [ColumnName("SkillsCombinationRarity"), LoadColumn(2)]
        public float SkillsCombinationRarity { get; set; }


        [ColumnName("SkillsCombinationRarityPerCrewRarity"), LoadColumn(3)]
        public float SkillsCombinationRarityPerCrewRarity { get; set; }


        [ColumnName("MaxRarity"), LoadColumn(4)]
        public float MaxRarity { get; set; }


        [ColumnName("VoyRank"), LoadColumn(5)]
        public float VoyRank { get; set; }


        [ColumnName("GauntletRank"), LoadColumn(6)]
        public float GauntletRank { get; set; }


        [ColumnName("ScienceSkillCore"), LoadColumn(7)]
        public float ScienceSkillCore { get; set; }


        [ColumnName("ScienceSkillRangeMin"), LoadColumn(8)]
        public float ScienceSkillRangeMin { get; set; }


        [ColumnName("ScienceSkillRangeMax"), LoadColumn(9)]
        public float ScienceSkillRangeMax { get; set; }


        [ColumnName("SecuritySkillCore"), LoadColumn(10)]
        public float SecuritySkillCore { get; set; }


        [ColumnName("SecuritySkillRangeMin"), LoadColumn(11)]
        public float SecuritySkillRangeMin { get; set; }


        [ColumnName("SecuritySkillRangeMax"), LoadColumn(12)]
        public float SecuritySkillRangeMax { get; set; }


        [ColumnName("CommandSkillCore"), LoadColumn(13)]
        public float CommandSkillCore { get; set; }


        [ColumnName("CommandSkillRangeMin"), LoadColumn(14)]
        public float CommandSkillRangeMin { get; set; }


        [ColumnName("CommandSkillRangeMax"), LoadColumn(15)]
        public float CommandSkillRangeMax { get; set; }


        [ColumnName("DiplomacySkillCore"), LoadColumn(16)]
        public float DiplomacySkillCore { get; set; }


        [ColumnName("DiplomacySkillRangeMin"), LoadColumn(17)]
        public float DiplomacySkillRangeMin { get; set; }


        [ColumnName("DiplomacySkillRangeMax"), LoadColumn(18)]
        public float DiplomacySkillRangeMax { get; set; }


        [ColumnName("EngineeringSkillCore"), LoadColumn(19)]
        public float EngineeringSkillCore { get; set; }


        [ColumnName("EngineeringSkillRangeMin"), LoadColumn(20)]
        public float EngineeringSkillRangeMin { get; set; }


        [ColumnName("EngineeringSkillRangeMax"), LoadColumn(21)]
        public float EngineeringSkillRangeMax { get; set; }


        [ColumnName("MedicineSkillCore"), LoadColumn(22)]
        public float MedicineSkillCore { get; set; }


        [ColumnName("MedicineSkillRangeMin"), LoadColumn(23)]
        public float MedicineSkillRangeMin { get; set; }


        [ColumnName("MedicineSkillRangeMax"), LoadColumn(24)]
        public float MedicineSkillRangeMax { get; set; }


        [ColumnName("B_CMD"), LoadColumn(25)]
        public float B_CMD { get; set; }


        [ColumnName("A_CMD"), LoadColumn(26)]
        public float A_CMD { get; set; }


        [ColumnName("B_SCI"), LoadColumn(27)]
        public float B_SCI { get; set; }


        [ColumnName("A_SCI"), LoadColumn(28)]
        public float A_SCI { get; set; }


        [ColumnName("B_SEC"), LoadColumn(29)]
        public float B_SEC { get; set; }


        [ColumnName("A_SEC"), LoadColumn(30)]
        public float A_SEC { get; set; }


        [ColumnName("V_CMD_SCI"), LoadColumn(31)]
        public float V_CMD_SCI { get; set; }


        [ColumnName("G_CMD_SCI"), LoadColumn(32)]
        public float G_CMD_SCI { get; set; }


        [ColumnName("V_CMD_SEC"), LoadColumn(33)]
        public float V_CMD_SEC { get; set; }


        [ColumnName("G_CMD_SEC"), LoadColumn(34)]
        public float G_CMD_SEC { get; set; }


        [ColumnName("V_CMD_ENG"), LoadColumn(35)]
        public float V_CMD_ENG { get; set; }


        [ColumnName("G_CMD_ENG"), LoadColumn(36)]
        public float G_CMD_ENG { get; set; }


        [ColumnName("V_CMD_DIP"), LoadColumn(37)]
        public float V_CMD_DIP { get; set; }


        [ColumnName("G_CMD_DIP"), LoadColumn(38)]
        public float G_CMD_DIP { get; set; }


        [ColumnName("V_CMD_MED"), LoadColumn(39)]
        public float V_CMD_MED { get; set; }


        [ColumnName("G_CMD_MED"), LoadColumn(40)]
        public float G_CMD_MED { get; set; }


        [ColumnName("V_SCI_SEC"), LoadColumn(41)]
        public float V_SCI_SEC { get; set; }


        [ColumnName("G_SCI_SEC"), LoadColumn(42)]
        public float G_SCI_SEC { get; set; }


        [ColumnName("V_SCI_ENG"), LoadColumn(43)]
        public float V_SCI_ENG { get; set; }


        [ColumnName("G_SCI_ENG"), LoadColumn(44)]
        public float G_SCI_ENG { get; set; }


        [ColumnName("V_SCI_DIP"), LoadColumn(45)]
        public float V_SCI_DIP { get; set; }


        [ColumnName("G_SCI_DIP"), LoadColumn(46)]
        public float G_SCI_DIP { get; set; }


        [ColumnName("V_SCI_MED"), LoadColumn(47)]
        public float V_SCI_MED { get; set; }


        [ColumnName("G_SCI_MED"), LoadColumn(48)]
        public float G_SCI_MED { get; set; }


        [ColumnName("V_SEC_ENG"), LoadColumn(49)]
        public float V_SEC_ENG { get; set; }


        [ColumnName("G_SEC_ENG"), LoadColumn(50)]
        public float G_SEC_ENG { get; set; }


        [ColumnName("V_SEC_DIP"), LoadColumn(51)]
        public float V_SEC_DIP { get; set; }


        [ColumnName("G_SEC_DIP"), LoadColumn(52)]
        public float G_SEC_DIP { get; set; }


        [ColumnName("V_SEC_MED"), LoadColumn(53)]
        public float V_SEC_MED { get; set; }


        [ColumnName("G_SEC_MED"), LoadColumn(54)]
        public float G_SEC_MED { get; set; }


        [ColumnName("V_ENG_DIP"), LoadColumn(55)]
        public float V_ENG_DIP { get; set; }


        [ColumnName("V_ENG_MED"), LoadColumn(56)]
        public float V_ENG_MED { get; set; }


        [ColumnName("V_DIP_MED"), LoadColumn(57)]
        public float V_DIP_MED { get; set; }


        [ColumnName("EventsCount"), LoadColumn(58)]
        public float EventsCount { get; set; }


        [ColumnName("IsInPortal"), LoadColumn(59)]
        public bool IsInPortal { get; set; }


        [ColumnName("DaysFromDateAdded"), LoadColumn(60)]
        public float DaysFromDateAdded { get; set; }


        [ColumnName("InCollectionsCount"), LoadColumn(61)]
        public float InCollectionsCount { get; set; }


        [ColumnName("IsInSeries_ds9"), LoadColumn(62)]
        public bool IsInSeries_ds9 { get; set; }


        [ColumnName("IsInSeries_dsc"), LoadColumn(63)]
        public bool IsInSeries_dsc { get; set; }


        [ColumnName("IsInSeries_ent"), LoadColumn(64)]
        public bool IsInSeries_ent { get; set; }


        [ColumnName("IsInSeries_original"), LoadColumn(65)]
        public bool IsInSeries_original { get; set; }


        [ColumnName("IsInSeries_pic"), LoadColumn(66)]
        public bool IsInSeries_pic { get; set; }


        [ColumnName("IsInSeries_tas"), LoadColumn(67)]
        public bool IsInSeries_tas { get; set; }


        [ColumnName("IsInSeries_tng"), LoadColumn(68)]
        public bool IsInSeries_tng { get; set; }


        [ColumnName("IsInSeries_tos"), LoadColumn(69)]
        public bool IsInSeries_tos { get; set; }


        [ColumnName("IsInSeries_voy"), LoadColumn(70)]
        public bool IsInSeries_voy { get; set; }


        [ColumnName("ShipBattleAccuracyMax"), LoadColumn(71)]
        public float ShipBattleAccuracyMax { get; set; }


        [ColumnName("ShipBattleEvasionMax"), LoadColumn(72)]
        public float ShipBattleEvasionMax { get; set; }


        [ColumnName("ShipBattleCritChanceMax"), LoadColumn(73)]
        public float ShipBattleCritChanceMax { get; set; }


        [ColumnName("ShipBattleCritBonusMax"), LoadColumn(74)]
        public float ShipBattleCritBonusMax { get; set; }


        [ColumnName("ActionBonusAmount"), LoadColumn(75)]
        public float ActionBonusAmount { get; set; }


        [ColumnName("ActionCooldown"), LoadColumn(76)]
        public float ActionCooldown { get; set; }


        [ColumnName("ActionInitialCooldown"), LoadColumn(77)]
        public float ActionInitialCooldown { get; set; }


        [ColumnName("ActionDuration"), LoadColumn(78)]
        public float ActionDuration { get; set; }


        [ColumnName("ActionLimit"), LoadColumn(79)]
        public float ActionLimit { get; set; }


        [ColumnName("ActionBonusType"), LoadColumn(80)]
        public float ActionBonusType { get; set; }


        [ColumnName("ActionAbilityCondition"), LoadColumn(81)]
        public float ActionAbilityCondition { get; set; }


        [ColumnName("ActionAbilityType"), LoadColumn(82)]
        public float ActionAbilityType { get; set; }


        [ColumnName("ActionAbilityAmount"), LoadColumn(83)]
        public float ActionAbilityAmount { get; set; }


        [ColumnName("ActionPenaltyType"), LoadColumn(84)]
        public float ActionPenaltyType { get; set; }


        [ColumnName("ActionPenaltyAmount"), LoadColumn(85)]
        public float ActionPenaltyAmount { get; set; }


        [ColumnName("TraitsCount"), LoadColumn(86)]
        public float TraitsCount { get; set; }


        [ColumnName("Traits"), LoadColumn(87)]
        public string Traits { get; set; }


        [ColumnName("TraitsHidden"), LoadColumn(88)]
        public string TraitsHidden { get; set; }


        [ColumnName("Name"), LoadColumn(89)]
        public string Name { get; set; }


    }
}
